# üß© Proceso de Extracci√≥n de Datos

Este notebook se encarga de la **extracci√≥n de datos** desde archivos CSV, bases de datos o cualquier otra fuente externa. El objetivo es obtener la informaci√≥n cruda necesaria para los siguientes procesos del ETL.

## ‚ú≥Ô∏è Librer√≠as necesarias

## Importaciones necesarias para el proceso de extraccion

In [ ]:
!pip install pandas
import pandas as pd

## Inscritos

In [ ]:

df_inscrito = pd.read_csv("/Users/monky02/Desktop/FP/DataOrigin/alr_inscritos.csv")
df_inscrito.head()

,id,nombres,apellidos,dni,pais,ciudad,institucion,profesion,cargo,telefono,...,direccion,correo,skype,grupo_trabajo,det1,det2,nombre_fac,ruc_fac,direccion_fac,telf_fac
0,4,Adriano,Fiorese,74347233949,Brasil,Joinville,Universidade do Estado de Santa Catarina - UDESC,Professor,Professor Universit√É¬°rio,0055 47 3481 7991,...,"Rua Paulo Malschitzki, 200 Zona Industrial Nor...",adriano.fiorese@udesc.br,af_udesc,NaN,NaN,0,NaN,NaN,NaN,NaN
1,6,Patricia Mar√É¬≠a,Henr√É¬≠quez Coronel,1757101678,Ecuador,Manta,Universidad Laica Eloy Alfaro de Manabi,PhD en Pedagog√É¬≠a,Profesora Titular Principal,+5930969142352,...,Ciudadela Altos de Manta Beach Torre 6 Dpto 2,patricia.henriquez@uleam.edu.ec,patricia henriquez-coronel,Investigaci√É¬≥n en Educaci√É¬≥n y Tecnolog√É¬≠a - I...,NaN,0,Patricia Henriquez C.,1757101678,Manta,0969142352
2,7,Patricia Mar√É¬≠a,Henr√É¬≠quez Coronel,1757101678,Ecuador,Manta,Universidad Laica Eloy Alfaro de Manabi,PhD en Pedagog√É¬≠a,Profesora Titular Principal,+5930969142352,...,Ciudadela Altos de Manta Beach Torre 6 Dpto 2,patricia.henriquez@uleam.edu.ec,patricia henriquez-coronel,Investigaci√É¬≥n en Educaci√É¬≥n y Tecnolog√É¬≠a - I...,NaN,0,Patricia Henriquez C.,1757101678,Manta,0969142352
3,8,C√É¬©sar Miguel,Oviedo Salinas,4385470,Paraguay,Villeta,Facultad de Ciencias Qu√É¬≠micas,Ingeniero Qu√É¬≠mico,Docente,021585562,...,Ciudad Universitaria,coviedo@qui.una.py,cesarmiguelo28@hotmail.com,Universidad Nacional de Asunci√É¬≥n,NaN,0,Facultad de Ciencias Qu√É¬≠micas,80010887-6,Campus Universitario,021585562
4,9,JOSILENE,MOREIRA,759165,Brasil,Joao Pessoa,Universidade Federal da Para√É¬≠ba,Analista de Sistemas,Professora,+351926172149,...,"Av. Cabo Branco, 3320",josileneaires@gmail.com,NaN,NaN,NaN,0,JOSILENE AIRES MOREIRA,Projeto Meninas,UFPB - Av. dos Escoteiros s/n - Joao Pessoa - PB,NaN

In [ ]:


# Ver cu√°ntas filas y columnas hay
print("Dimensiones:", df_inscrito.shape)

# Ver columnas
print("Columnas:", df_inscrito.columns)

# Ver tipos de datos
print("Tipos de datos:")
print(df_inscrito.dtypes)

Dimensiones: (390, 3)
Columnas: Index(['idAsignatura', 'codigo', 'nombre'], dtype='object')
Tipos de datos:
idAsignatura     int64
codigo          object
nombre          object
dtype: object

## Asignatura

In [11]:
import pandas as pd
df_asignatura = pd.read_csv("/Users/monky02/Desktop/FP/DataOrigin/asignatura.csv")
df_asignatura.head()

   idAsignatura     codigo                               nombre
0             5  UTPLDG001                          Prototipado
1             6  UTPLRL001                       Ingenieria Web
2             7  UTPLRC001  Procesos de Ingenier√É¬≠a de Software
3             8  UTPLFC001              Computaci√É¬≥n y Sociedad
4             9  UTPLDI001                 Estructuras de datos

In [ ]:
# Ver cu√°ntas filas y columnas hay
print("Dimensiones:", df_asignatura.shape)

# Ver columnas
print("Columnas:", df_asignatura.columns)

# Ver tipos de datos
print("Tipos de datos:")
print(df_asignatura.dtypes)

Dimensiones: (390, 3)
Columnas: Index(['idAsignatura', 'codigo', 'nombre'], dtype='object')
Tipos de datos:
idAsignatura     int64
codigo          object
nombre          object
dtype: object

## Docente

In [ ]:

df_docente = pd.read_csv("/Users/monky02/Desktop/FP/DataOrigin/docente.csv")
df_docente.head()

,idDocente,nombres,identificacion,correo,rol,username,password
0,7,Ramiro Leonardo Ramirez Coronel Administrador,1104076797,rlramirez@utpl.edu.ec,1.0,rlramirez,6355200384765677651e075debb01ae0
1,9,Daniel Guam√É¬°n,1111111,daguaman@utpl.edu.ec,2.0,daguaman,75275e769db3b685af9bd9359be4ac9b
2,10,Roddy Correa,11111111,racorrea2@utpl.edu.ec,2.0,racorrea2,8dc4253bede219486fb1741d1f41d214
3,11,Fanny Cevallos,111111,fbcevallos@utpl.edu.ec,2.0,fbcevallos,a2371c2d05b8dd55701f2472dd6cacaf
4,13,Daniel Irene,111,pdirene@gmail.com,2.0,pdirene,095382c6221dd36799da3f7a55877bb2

In [14]:
# Ver cu√°ntas filas y columnas hay
print("Dimensiones:", df_docente.shape)

# Ver columnas
print("Columnas:", df_docente.columns)

# Ver tipos de datos
print("Tipos de datos:")
print(df_docente.dtypes)

Dimensiones: (232, 7)
Columnas: Index(['idDocente', 'nombres', 'identificacion', 'correo', 'rol', 'username',
       'password'],
      dtype='object')
Tipos de datos:
idDocente           int64
nombres            object
identificacion      int64
correo             object
rol               float64
username           object
password           object
dtype: object

## Docente Asignatura

In [ ]:

df_docenteAsignatura = pd.read_csv("/Users/monky02/Desktop/FP/DataOrigin/docenteasignatura.csv")
df_docenteAsignatura.head()

   id  idDocente  idAsignatura
0   7          9             5
1   8          7             6
2   9         10             7
3  10         11             8
4  12         13             9

In [16]:
# Ver cu√°ntas filas y columnas hay
print("Dimensiones:", df_docenteAsignatura.shape)

# Ver columnas
print("Columnas:", df_docenteAsignatura.columns)

# Ver tipos de datos
print("Tipos de datos:")
print(df_docenteAsignatura.dtypes)

Dimensiones: (388, 3)
Columnas: Index(['id', 'idDocente', 'idAsignatura'], dtype='object')
Tipos de datos:
id              int64
idDocente       int64
idAsignatura    int64
dtype: object

## Result classs

In [ ]:

df_docenteAsignatura = pd.read_csv("/Users/monky02/Desktop/FP/DataOrigin/result_class.csv")
df_docenteAsignatura.head()

,id,random,fecha,UIDE,val_class,senti1,senti2,senti3,senti4,senti5,senti6,senti7,senti8,senti9,senti10,det
0,31,7530,2020-04-14 01:20:28,Comentarios..,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,181.113.149.199
1,32,6541,2020-04-14 11:07:07,Comentarios..,4,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,181.113.149.199
2,33,7530,2020-04-14 11:13:34,Comentarios..,0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,190.96.96.147
3,34,8873,2020-04-14 20:39:10,Comentarios..,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,186.70.43.40
4,35,8873,2020-04-14 20:39:21,La clase muy buena y entretenida.,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,186.178.106.190

In [18]:
# Ver cu√°ntas filas y columnas hay
print("Dimensiones:", df_docenteAsignatura.shape)

# Ver columnas
print("Columnas:", df_docenteAsignatura.columns)

# Ver tipos de datos
print("Tipos de datos:")
print(df_docenteAsignatura.dtypes)

Dimensiones: (13696, 16)
Columnas: Index(['id', 'random', 'fecha', 'UIDE', 'val_class', 'senti1', 'senti2',
       'senti3', 'senti4', 'senti5', 'senti6', 'senti7', 'senti8', 'senti9',
       'senti10', 'det'],
      dtype='object')
Tipos de datos:
id             int64
random         int64
fecha         object
UIDE          object
val_class      int64
senti1       float64
senti2       float64
senti3       float64
senti4       float64
senti5       float64
senti6       float64
senti7       float64
senti8       float64
senti9       float64
senti10      float64
det           object
dtype: object

In [22]:
df_inscrito = pd.read_csv("/Users/monky02/Desktop/FP/DataOrigin/alr_inscritos.csv", encoding='utf-8', )

print(df_inscrito)

      id            nombres           apellidos          dni         pais  \
0      4            Adriano             Fiorese  74347233949       Brasil
1      6    Patricia Mar√É¬≠a  Henr√É¬≠quez Coronel   1757101678      Ecuador
2      7    Patricia Mar√É¬≠a  Henr√É¬≠quez Coronel   1757101678      Ecuador
3      8      C√É¬©sar Miguel      Oviedo Salinas      4385470     Paraguay
4      9           JOSILENE             MOREIRA       759165       Brasil
..   ...                ...                 ...          ...          ...
731  881  Jhonnattan Steven        Prieto Perez   1098310208     Colombia
732  882  Jhonnattan Steven        Prieto Perez   1098310208     Colombia
733  883     Marvin Armando      Castro Rold√É¬°n    305070939  Afganist√É¬°n
734  884           santiago               lopez      AV95555     Colombia
735  885             Hshshs             Hshshsh      1122888  Afganist√É¬°n

          ciudad                                       institucion  \
0      Joinville  Universidade do Estado de Santa Catarina - UDESC
1          Manta           Universidad Laica Eloy Alfaro de Manabi
2          Manta           Universidad Laica Eloy Alfaro de Manabi
3        Villeta                    Facultad de Ciencias Qu√É¬≠micas
4    Joao Pessoa                  Universidade Federal da Para√É¬≠ba
..           ...                                               ...
731          NaN                                               NaN
732          NaN                                               NaN
733      Cartago                                               NaN
734      Armenia                           Universidad del Quindio
735     Jdkdkdjd                                               NaN

                profesion                        cargo           telefono  \
0               Professor     Professor Universit√É¬°rio  0055 47 3481 7991
1       PhD en Pedagog√É¬≠a  Profesora Titular Principal     +5930969142352
2       PhD en Pedagog√É¬≠a  Profesora Titular Principal     +5930969142352
3      Ingeniero Qu√É¬≠mico                      Docente          021585562
4    Analista de Sistemas                   Professora      +351926172149
..                    ...                          ...                ...
731                   NaN                          NaN         3147665949
732                   NaN                          NaN         3147665949
733                   NaN                          NaN           83362273
734            Estudiante                   Estudiante         5169128833
735                   NaN                          NaN             112588

     ...                                          direccion  \
0    ...  Rua Paulo Malschitzki, 200 Zona Industrial Nor...
1    ...      Ciudadela Altos de Manta Beach Torre 6 Dpto 2
2    ...      Ciudadela Altos de Manta Beach Torre 6 Dpto 2
3    ...                               Ciudad Universitaria
4    ...                              Av. Cabo Branco, 3320
..   ...                                                ...
731  ...                                           Calle 12
732  ...                                           Calle 12
733  ...                                Cartago,Barrio Asis
734  ...                                   229 Linnmoore st
735  ...                                       Jsjsgdjsnsks

                              correo                       skype  \
0           adriano.fiorese@udesc.br                    af_udesc
1    patricia.henriquez@uleam.edu.ec  patricia henriquez-coronel
2    patricia.henriquez@uleam.edu.ec  patricia henriquez-coronel
3                 coviedo@qui.una.py  cesarmiguelo28@hotmail.com
4            josileneaires@gmail.com                         NaN
..                               ...                         ...
731     jsprietop_1@uqvirtual.edu.co                     General
732     jsprietop_1@uqvirtual.edu.co                     General
733              marcasro9@gmail.com                     General
734         linalopez460@hotmail.com                     General
735                          h@h.com                     General

                                         grupo_trabajo   det1          det2  \
0                                                  NaN    NaN             0
1    Investigaci√É¬≥n en Educaci√É¬≥n y Tecnolog√É¬≠a - I...    NaN             0
2    Investigaci√É¬≥n en Educaci√É¬≥n y Tecnolog√É¬≠a - I...    NaN             0
3                    Universidad Nacional de Asunci√É¬≥n    NaN             0
4                                                  NaN    NaN             0
..                                                 ...    ...           ...
731                                                NaN   50.0  123456789 -
732                                                NaN   50.0  123456789 -
733                                                NaN  180.0           NaN
734                                               CRAI  180.0      sv232 -
735                                                NaN  180.0           NaN

                         nombre_fac          ruc_fac  \
0                               NaN              NaN
1             Patricia Henriquez C.       1757101678
2             Patricia Henriquez C.       1757101678
3    Facultad de Ciencias Qu√É¬≠micas       80010887-6
4            JOSILENE AIRES MOREIRA  Projeto Meninas
..                              ...              ...
731                             NaN              NaN
732                             NaN              NaN
733   Marvin Armando Castro Rold√É¬°n              NaN
734                             NaN              NaN
735                             NaN              NaN

                                        direccion_fac    telf_fac
0                                                 NaN         NaN
1                                               Manta  0969142352
2                                               Manta  0969142352
3                                Campus Universitario   021585562
4    UFPB - Av. dos Escoteiros s/n - Joao Pessoa - PB         NaN
..                                                ...         ...
731                                               NaN         NaN
732                                               NaN         NaN
733                                               NaN         NaN
734                                               NaN         NaN
735                                               NaN         NaN

[736 rows x 21 columns]

-- -